
{"level":"error"}
{"level":"error"}
{"date":"Fri Aug 16 2024 16:05:17 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":515909.39},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18298633,"external":20731807,"heapTotal":59478016,"heapUsed":25196424,"rss":75751424},"pid":47644,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$jqXp3d7LJVsFG0oiLCAETug7V3DAjSzI32hC3CUPAqjMaEn0aezYm`) is longer than the maximum allowed length (13).","name":"ValidatorError","path":"Password","properties":{"maxlength":13,"message":"Path `Password` (`$2b$10$jqXp3d7LJVsFG0oiLCAETug7V3DAjSzI32hC3CUPAqjMaEn0aezYm`) is longer than the maximum allowed length (13).","path":"Password","type":"maxlength","value":"$2b$10$jqXp3d7LJVsFG0oiLCAETug7V3DAjSzI32hC3CUPAqjMaEn0aezYm"},"value":"$2b$10$jqXp3d7LJVsFG0oiLCAETug7V3DAjSzI32hC3CUPAqjMaEn0aezYm"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$jqXp3d7LJVsFG0oiLCAETug7V3DAjSzI32hC3CUPAqjMaEn0aezYm`) is longer than the maximum allowed length (13).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:08:15 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516087.046},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18304037,"external":20736116,"heapTotal":27758592,"heapUsed":24767624,"rss":45867008},"pid":10776,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$hT5YZIDvvxc0fuIDWgtl6eRnBcZaz00G7NeshCFuc9rCRxezHozsa`) is longer than the maximum allowed length (13).","name":"ValidatorError","path":"Password","properties":{"maxlength":13,"message":"Path `Password` (`$2b$10$hT5YZIDvvxc0fuIDWgtl6eRnBcZaz00G7NeshCFuc9rCRxezHozsa`) is longer than the maximum allowed length (13).","path":"Password","type":"maxlength","value":"$2b$10$hT5YZIDvvxc0fuIDWgtl6eRnBcZaz00G7NeshCFuc9rCRxezHozsa"},"value":"$2b$10$hT5YZIDvvxc0fuIDWgtl6eRnBcZaz00G7NeshCFuc9rCRxezHozsa"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$hT5YZIDvvxc0fuIDWgtl6eRnBcZaz00G7NeshCFuc9rCRxezHozsa`) is longer than the maximum allowed length (13).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:10:38 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516229.875},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18340928,"external":20774122,"heapTotal":59740160,"heapUsed":27080712,"rss":45355008},"pid":43676,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$tk2XMoK.RMT2uuFiqRKqb.FnRC1hkwCj4H5XVGnmMBmi0EJOFMuya`) is longer than the maximum allowed length (13).","name":"ValidatorError","path":"Password","properties":{"maxlength":13,"message":"Path `Password` (`$2b$10$tk2XMoK.RMT2uuFiqRKqb.FnRC1hkwCj4H5XVGnmMBmi0EJOFMuya`) is longer than the maximum allowed length (13).","path":"Password","type":"maxlength","value":"$2b$10$tk2XMoK.RMT2uuFiqRKqb.FnRC1hkwCj4H5XVGnmMBmi0EJOFMuya"},"value":"$2b$10$tk2XMoK.RMT2uuFiqRKqb.FnRC1hkwCj4H5XVGnmMBmi0EJOFMuya"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$tk2XMoK.RMT2uuFiqRKqb.FnRC1hkwCj4H5XVGnmMBmi0EJOFMuya`) is longer than the maximum allowed length (13).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:13:17 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516389.375},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18340912,"external":20776722,"heapTotal":59740160,"heapUsed":30032048,"rss":75964416},"pid":42048,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$HgvSaSZXFD9ZZQ0iSId0xuiOFDvU7f8Y1yLKawM0rESyaUf7uGlLW`) is longer than the maximum allowed length (13).","name":"ValidatorError","path":"Password","properties":{"maxlength":13,"message":"Path `Password` (`$2b$10$HgvSaSZXFD9ZZQ0iSId0xuiOFDvU7f8Y1yLKawM0rESyaUf7uGlLW`) is longer than the maximum allowed length (13).","path":"Password","type":"maxlength","value":"$2b$10$HgvSaSZXFD9ZZQ0iSId0xuiOFDvU7f8Y1yLKawM0rESyaUf7uGlLW"},"value":"$2b$10$HgvSaSZXFD9ZZQ0iSId0xuiOFDvU7f8Y1yLKawM0rESyaUf7uGlLW"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$HgvSaSZXFD9ZZQ0iSId0xuiOFDvU7f8Y1yLKawM0rESyaUf7uGlLW`) is longer than the maximum allowed length (13).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:14:04 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516435.812},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18347301,"external":20780495,"heapTotal":59740160,"heapUsed":27092904,"rss":76038144},"pid":50224,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$4fJwMu2nSbUSi60L2Jesi.fdb0JK5PZZPhhbjHCvoTMHnJaoBbUNe`) is longer than the maximum allowed length (52).","name":"ValidatorError","path":"Password","properties":{"maxlength":52,"message":"Path `Password` (`$2b$10$4fJwMu2nSbUSi60L2Jesi.fdb0JK5PZZPhhbjHCvoTMHnJaoBbUNe`) is longer than the maximum allowed length (52).","path":"Password","type":"maxlength","value":"$2b$10$4fJwMu2nSbUSi60L2Jesi.fdb0JK5PZZPhhbjHCvoTMHnJaoBbUNe"},"value":"$2b$10$4fJwMu2nSbUSi60L2Jesi.fdb0JK5PZZPhhbjHCvoTMHnJaoBbUNe"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$4fJwMu2nSbUSi60L2Jesi.fdb0JK5PZZPhhbjHCvoTMHnJaoBbUNe`) is longer than the maximum allowed length (52).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:15:06 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516498.203},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18347897,"external":20783707,"heapTotal":59740160,"heapUsed":30136992,"rss":76603392},"pid":12856,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$QgnoFOMKw2/m/A2IjD7nyegsh99m4fpn8GvHlybaPJL4DeVV3Exj2`) is longer than the maximum allowed length (52).","name":"ValidatorError","path":"Password","properties":{"maxlength":52,"message":"Path `Password` (`$2b$10$QgnoFOMKw2/m/A2IjD7nyegsh99m4fpn8GvHlybaPJL4DeVV3Exj2`) is longer than the maximum allowed length (52).","path":"Password","type":"maxlength","value":"$2b$10$QgnoFOMKw2/m/A2IjD7nyegsh99m4fpn8GvHlybaPJL4DeVV3Exj2"},"value":"$2b$10$QgnoFOMKw2/m/A2IjD7nyegsh99m4fpn8GvHlybaPJL4DeVV3Exj2"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$QgnoFOMKw2/m/A2IjD7nyegsh99m4fpn8GvHlybaPJL4DeVV3Exj2`) is longer than the maximum allowed length (52).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:15:39 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516531.312},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18340928,"external":20776738,"heapTotal":59740160,"heapUsed":30036336,"rss":64307200},"pid":49076,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$gNFIYIrq23zml.LcnYFcf.V3W3Sfais48T9KDl2YJWqOac6r53UV6`) is longer than the maximum allowed length (52).","name":"ValidatorError","path":"Password","properties":{"maxlength":52,"message":"Path `Password` (`$2b$10$gNFIYIrq23zml.LcnYFcf.V3W3Sfais48T9KDl2YJWqOac6r53UV6`) is longer than the maximum allowed length (52).","path":"Password","type":"maxlength","value":"$2b$10$gNFIYIrq23zml.LcnYFcf.V3W3Sfais48T9KDl2YJWqOac6r53UV6"},"value":"$2b$10$gNFIYIrq23zml.LcnYFcf.V3W3Sfais48T9KDl2YJWqOac6r53UV6"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$gNFIYIrq23zml.LcnYFcf.V3W3Sfais48T9KDl2YJWqOac6r53UV6`) is longer than the maximum allowed length (52).","name":"ValidationError"}
{"date":"Fri Aug 16 2024 16:18:54 GMT+0300 (توقيت شرق أوروبا الصيفي)","error":{},"level":"error","message":"unhandledRejection: Method no longer accepts array arguments: valid\nError: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","os":{"loadavg":[0,0,0],"uptime":516726.234},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\backend\\practiece\\server.js"],"cwd":"E:\\backend\\practiece","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18340928,"external":20776738,"heapTotal":59740160,"heapUsed":30125832,"rss":76591104},"pid":43784,"uid":null,"version":"v20.11.1"},"rejection":true,"stack":"Error: Method no longer accepts array arguments: valid\n    at new module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js:23:19)\n    at module.exports (E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js:21:11)\n    at exports.verifyFlat (E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js:214:9)\n    at internals.Base.valid (E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js:297:16)\n    at validateUser (E:\\backend\\practiece\\module\\user.js:108:29)\n    at E:\\backend\\practiece\\router\\home.js:45:19\n    at newFn (E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js:119:3)","trace":[{"column":19,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\error.js","function":"new module.exports","line":23,"method":"exports","native":false},{"column":11,"file":"E:\\backend\\practiece\\node_modules\\@hapi\\hoek\\lib\\assert.js","function":"module.exports","line":21,"method":"exports","native":false},{"column":9,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\common.js","function":"exports.verifyFlat","line":214,"method":"verifyFlat","native":false},{"column":16,"file":"E:\\backend\\practiece\\node_modules\\joi\\lib\\base.js","function":"internals.Base.valid","line":297,"method":"valid","native":false},{"column":29,"file":"E:\\backend\\practiece\\module\\user.js","function":"validateUser","line":108,"method":null,"native":false},{"column":19,"file":"E:\\backend\\practiece\\router\\home.js","function":null,"line":45,"method":null,"native":false},{"column":20,"file":"E:\\backend\\practiece\\node_modules\\express-async-errors\\index.js","function":"newFn","line":16,"method":null,"native":false},{"column":5,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"next","line":149,"method":null,"native":false},{"column":3,"file":"E:\\backend\\practiece\\node_modules\\express\\lib\\router\\route.js","function":"Route.dispatch","line":119,"method":"dispatch","native":false}]}
{"_message":"user validation failed","errors":{"Password":{"kind":"maxlength","message":"Path `Password` (`$2b$10$0riVokLkZ4VVX14pnM3j3uvRCSDrtt0etZVpEoQ19FQdE.dPDK6LG`) is longer than the maximum allowed length (52).","name":"ValidatorError","path":"Password","properties":{"maxlength":52,"message":"Path `Password` (`$2b$10$0riVokLkZ4VVX14pnM3j3uvRCSDrtt0etZVpEoQ19FQdE.dPDK6LG`) is longer than the maximum allowed length (52).","path":"Password","type":"maxlength","value":"$2b$10$0riVokLkZ4VVX14pnM3j3uvRCSDrtt0etZVpEoQ19FQdE.dPDK6LG"},"value":"$2b$10$0riVokLkZ4VVX14pnM3j3uvRCSDrtt0etZVpEoQ19FQdE.dPDK6LG"}},"level":"info","message":"user validation failed: Password: Path `Password` (`$2b$10$0riVokLkZ4VVX14pnM3j3uvRCSDrtt0etZVpEoQ19FQdE.dPDK6LG`) is longer than the maximum allowed length (52).","name":"ValidationError"}
{"level":"error"}
{"_message":"user validation failed","errors":{"Type":{"kind":"enum","message":"`trainner` is not a valid enum value for path `Type`.","name":"ValidatorError","path":"Type","properties":{"enumValues":["trinare","perante","fighter"],"message":"`trainner` is not a valid enum value for path `Type`.","path":"Type","type":"enum","value":"trainner"},"value":"trainner"}},"level":"info","message":"user validation failed: Type: `trainner` is not a valid enum value for path `Type`.","name":"ValidationError"}
{"_message":"user validation failed","errors":{"Type":{"kind":"enum","message":"`trainner` is not a valid enum value for path `Type`.","name":"ValidatorError","path":"Type","properties":{"enumValues":["trainnare","perante","fighter"],"message":"`trainner` is not a valid enum value for path `Type`.","path":"Type","type":"enum","value":"trainner"},"value":"trainner"}},"level":"info","message":"user validation failed: Type: `trainner` is not a valid enum value for path `Type`.","name":"ValidationError"}
{"level":"info","message":"wrong in connect Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.yniqbhl.mongodb.net"}
{"level":"info","message":"wrong in connect Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.yniqbhl.mongodb.net"}
